version: '3'

services:
  app:
    container_name: todo-list-api-nest
    build: .
    ports:
      - '3000:3000'
    environment:
      APP_NAME: todo-list-api-nest
      VERSION: ${VERSION}
      COMMIT_ID: ${COMMIT_ID}
      PORT: 3000
